name: square_camera
description: Camera with a square prewiev, takes a picture, croppes it, saves file to the gallery.
repository: https://github.com/nzxcvbnm/camera
email: nmaslij.9@gmail.com

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  gallery_saver:
  image_picker:
  image_cropper:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
